### PR TITLE
Feature/color refactor

### LINKED ISSUE #50: Code Refactoring - Navigation

### PR DESCRIPTION
**Pull request by AdrielVBomfim**
This PR refactors how the colors are handled in the polkadex app. Now there is a class called AppColors which will have static const attributtes of the collors that the app needs to use.

Closes #50

### CODE REVIEW

**Comment by Gauthamastro** [comment]
@AdrielVBomfim Is this relevant anymore?

**Comment by AdrielVBomfim** [comment]
> @AdrielVBomfim Is this relevant anymore?

@Gauthamastro Yes it is, I didn't have the opportunity to come back to this PR because my current tasks have much higher priority.

**Comment by simonsso** [comment]
Converted this to a draft as it have huge merge conflclicts

**Comment by AdrielVBomfim** [comment]
Merge conflicts solved and app tested. Looks good :)

**Review by simonsso — COMMENTED** [review]
looks ok, is there anything we can do about the failing testcase?

**Comment by AdrielVBomfim** [comment]
> looks ok, is there anything we can do about the failing testcase?

The build failed because the biometric_storage has to be updated to version 4.0, so it's not related to this PR.

**Pull request merged**
